### ISSUE TITLE
i've had terrible experience with @stacks/connect > 6.0 and here's another example

### ISSUE THREAD

**Issue by dantrevino** [pradel/stacks-next-auth-example#2]
When trying to run the code, I get the following error:
```
error - ./node_modules/@stacks/auth/dist/polyfill/index.js:1:21
Module not found: Can't resolve '@stacks/common/dist/polyfill'
```

I tried explicitly installing @stacks/common, but no luck.

**Comment by pradel** [comment]
Pushed a commit to upgrade all the deps, hope this helps https://github.com/pradel/stacks-next-auth-example/commit/ec617838089e7c409b46582ab0f955965db8cf1a
